name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpUnitTests:
    runs-on: ubuntu-latest
    name: Unit Tests / PHP ${{ matrix.phpVersion }} / Winter ${{ matrix.winterRelease }}
    strategy:
      max-parallel: 6
      matrix:
        phpVersion: ['8.1']
        winterRelease: ['develop']
        winterReleaseDir: ['develop']
      fail-fast: false
    env:
      phpExtensions: mbstring, intl, gd, xml, sqlite
      cacheKey: ext-cache-v1
      winterCmsRelease: develop
    steps:
      - name: Checkout changes
        uses: actions/checkout@v4
        with:
          path: data-plugin

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.phpVersion }}
          extensions: ${{ env.phpExtensions }}
          key: ${{ env.cacheKey }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Install PHP and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}
          extensions: ${{ env.phpExtensions }}

      - name: Install Winter CMS
        run: |
          wget https://github.com/wintercms/winter/archive/${{ matrix.winterRelease }}.zip
          unzip ${{ matrix.winterRelease }}.zip
          rm ${{ matrix.winterRelease }}.zip
          shopt -s dotglob
          mv winter-${{ matrix.winterReleaseDir }}/* ./
          rmdir winter-${{ matrix.winterReleaseDir }}
          shopt -u dotglob
          cp config/cms.php config/testing/cms.php
          mkdir -p plugins/hounddd
          mv data-plugin plugins/hounddd/data

      - name: Get Composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Allow merge for plugins dependencies
        run: sed -i 's/myauthor\/\*/hounddd\/data/g' composer.json

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress

      # - name: Install plugin dependencies
      #   run: composer require spatie/laravel-data "^3.0" --no-ansi --no-interaction --no-progress

      # - name: Move plugin to plugins directory
      #   run: |
      #     mkdir -p plugins/hounddd
      #     mv data-plugin plugins/hounddd/data

      - name: Run linting
        run: ./vendor/bin/parallel-lint plugins/hounddd/data

      - name: Run unit tests (1.2/develop)
        if: matrix.winterRelease != 'v1.1.9'
        run: php artisan winter:test -p Hounddd.Data
